# Generated by Django 2.1.5 on 2019-03-14 18:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Higher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Type must be greater than 1 character')])),
            ],
        ),
        migrations.CreateModel(
            name='Lower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Nickname must be greater than 1 character')])),
                ('some_num_characteristic', models.PositiveIntegerField()),
                ('some_str_characteristic', models.PositiveIntegerField()),
                ('higher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Higher')),
            ],
        ),
    ]
