# Generated by Django 2.1.5 on 2019-03-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lower',
            old_name='some_num_characteristic',
            new_name='distance',
        ),
        migrations.RenameField(
            model_name='lower',
            old_name='some_str_characteristic',
            new_name='mass',
        ),
    ]
